#!/bin/bash -e
#
# S2I run script for the 'golang' image.
# The run script executes the server that runs your application.
#
# For more information see the documentation:
#	https://github.com/openshift/source-to-image/blob/master/docs/builder_image.md
#

# Load environment ${INSTALL_URL}
env_openshift=`find . -name ".env_openshift.sh"`
. ${env_openshift}

echo "Acessing app directory ${HOME}/${INSTALL_URL}"
pushd ${HOME}/${INSTALL_URL}

if [ "${RUN_DEP}" = true ]; then
  echo "Downloading dependencies"
  dep ensure
fi

if [ "${APP_ENV}" = "production" ]; then
  echo "Executing in production mode"

  go build -o main
  ./main
else
  echo "Executing in development (hot code) mode"
  ${GOBIN}/.air
fi
